network:
  version: 2
  renderer: networkd
  ethernets:
     eth0:
       dhcp4: yes
       dhcp6: no
       addresses:
         - 193.191.177.223/25
         - 2001:6a8:2880:a077::df/64
       gateway6:  2001:6a8:2880:a077::1
