#!/bin/bash

# must be root
if [ "$EUID" -ne 0 ]
  then
        echo "You have to be root to execute this"
        exit 0
fi

if  [[ $1 == "-t" ]]; then
	RECORD=$2
	SUB=$3
	IP=$4
	PARENT=$5
else
	RECORD="A"
	SUB=$1
	IP=$2
	PARENT=$3
fi

if [[ $RECORD == "A" ]]
then
	if [ -z "$SUB" ] || [ -z "$IP" ] || [ -z "$PARENT" ]
	then
		echo "Geef een parent, een ip en een subdomein in"
		exit 0;
	else
	        echo "$SUB	IN	A	$IP" >> /etc/bind/zones/db.$PARENT
        	PAD="/etc/bind/zones/db.$PARENT";
	fi
elif [[ $RECORD == "MX" ]]
then
        if [ -z "$SUB" ] || [ -z "$IP" ] || [ -z "$PARENT" ]
	then
		echo "Geef een parent, een ip en een subdomein in"
		exit 0;
	else
	        echo "@	IN	MX	10	$SUB.$PARENT." >> /etc/bind/zones/db.$PARENT
       		echo "$SUB	IN	A	$IP" >> /etc/bind/zones/db.$PARENT
        	PAD="/etc/bind/zones/db.$PARENT";
	fi
elif [[ $RECORD == "CNAME" ]]
then
        if [ -z "$SUB" ] || [ -z "$IP" ]
	then
		echo "Geef een parent en subdomein in"
		exit 0;
	else
	        echo "$SUB	IN	CNAME	$IP." >> /etc/bind/zones/db.$IP
        	PAD="/etc/bind/zones/db.$IP";
	fi
fi

# update serial
var="`grep -A 0 'Serial' $PAD | grep -oP '[0-9]*'`"
new=$((var+1))
echo "pad $PAD nieuw $new"
sed -i "s/.*Serial.*/\t\t\t     $new\t\t; Serial/g $PAD"

# reload file
rndc reload

# restart bind
systemctl restart bind9
