#!/bin/bash
# must be root
if [ "$EUID" -ne 0 ]
  then echo "You have to be root to execute this";
  exit 0;
fi

# domain
DOMAIN=$1

# check empty
if [ -z "$DOMAIN" ]
then
        echo "Geen domein naam gegeven"
	exit 0
fi


if [ ! -d "/var/www/html/$DOMAIN" ]
then
	echo "Domain $DOMAIN does not exist"
else
	# vhost
echo "<VirtualHost *:80>
    ServerName $DOMAIN
    DocumentRoot /var/www/html/$DOMAIN
    ErrorLog \${APACHE_LOG_DIR}/$DOMAIN-error.log
    CustomLog \${APACHE_LOG_DIR}/$DOMAIN-access.log combined
</VirtualHost>" >> "/etc/apache2/sites-available/$DOMAIN.conf"

	# create dir
#	mkdir "/var/www/html/$DOMAIN" && touch "/var/www/html/$DOMAIN/index.html"

	# vhost name in index
	echo "Welcome  $DOMAIN" >> "/var/www/html/$DOMAIN/index.html"

	# enable vhost
	a2ensite $DOMAIN

	# reload
	systemctl reload apache2
fi
